PK
FK
UNIQUE
INDEX
IDGENERATOR
SEQUENCE
SOFTDELETE
ASBOOLEAN

@startuml database

entity account {
    
    ==
    id : BIGINT(11) UNSIGNED PK AUTO_INCREMENT NOT NULL -- 
    user_id : VARCHAR(255) NULL -- user_id
    money : INT(11) DEFAULT 0 NULL -- 
    create_time : DATETIME NULL -- 
    update_time : DATETIME NULL -- 
}

@enduml