PK
FK
UNIQUE
INDEX
IDGENERATOR
SEQUENCE
SOFTDELETE
ASBOOLEAN

@startuml praise

entity item {
    
    ==
    id : BIGINT(11) UNSIGNED PK AUTO_INCREMENT NOT NULL -- 
    praise : INT(11) NULL -- 
    create_time : DATETIME NULL -- 
    update_time : DATETIME NULL -- 
}

@enduml