server:
  port: 8013

spring:
  application:
    name: integrated-order
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        group: integrated-example
      config:
        server-addr: nacos-server:8848
        group: integrated-example
        file-extension: yaml
  config:
    import:
      - optional:nacos:integrated-order.yaml
      - optional:nacos:datasource-config.yaml
      - optional:nacos:summer-config.yaml
      - optional:nacos:seata-config.yaml

