PK
FK
UNIQUE
INDEX
IDGENERATOR
SEQUENCE
SOFTDELETE
ASBOOLEAN

@startuml database

entity storage {
    
    ==
    id : BIGINT(11) UNSIGNED PK AUTO_INCREMENT NOT NULL -- 
    commodity_code : VARCHAR(255) UNIQUE NULL -- 
    count : INT(11) DEFAULT 0 NULL -- 
    create_time : DATETIME NULL -- 
    update_time : DATETIME NULL -- 
}

@enduml