server:
  port: 8011

spring:
  application:
    name: integrated-storage
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        group: integrated-example
      config:
        server-addr: nacos-server:8848
        group: integrated-example
  config:
    import:
      - optional:nacos:integrated-storage.yaml
      - optional:nacos:datasource-config.yaml
      - optional:nacos:summer-config.yaml
      - optional:nacos:seata-config.yaml


