PK
FK
UNIQUE
INDEX
IDGENERATOR
SEQUENCE
SOFTDELETE
ASBOOLEAN

@startuml order

entity order {
    
    ==
    id : BIGINT(11) UNSIGNED PK AUTO_INCREMENT NOT NULL -- 
    user_id : VARCHAR(255) NULL -- 
    commodity_code : VARCHAR(255) NULL -- 
    count : INT(11) NULL -- 
    money : INT(11) DEFAULT 0 NULL -- 
    create_time : DATETIME NULL -- 
    update_time : DATETIME NULL -- 
}

@enduml